[package]
name = "."
version = "0.1"
lean_version = "leanprover-community/lean:3.42.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "1494a9b2c48c9dcf92848910414eacb9257bce1d"}

#lean-gptf = {path = "/home/dwrensha/src/lean-gptf" }