[package]
name = "."
version = "0.1"
lean_version = "leanprover-community/lean:3.32.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "8f863f6b32bb80706cd7c6c0c0f0182f13d00e7a"}

#lean-gptf = {path = "/home/dwrensha/src/lean-gptf" }