[package]
name = "."
version = "0.1"
lean_version = "leanprover-community/lean:3.30.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "6e5899ddad9855e54f9d340493b31b92ae5b0084"}

#lean-gptf = {path = "/home/dwrensha/src/lean-gptf" }