[package]
name = "."
version = "0.1"
lean_version = "leanprover-community/lean:3.31.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "6fa678fb54adcb2f85b3dea1c50c4df26361330a"}

#lean-gptf = {path = "/home/dwrensha/src/lean-gptf" }