[package]
name = "."
version = "0.1"
lean_version = "leanprover-community/lean:3.35.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "044f5320a5b3f01ba0e3693949ebf1ab62e39399"}

#lean-gptf = {path = "/home/dwrensha/src/lean-gptf" }