[package]
name = "."
version = "0.1"
lean_version = "leanprover-community/lean:3.43.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "988f160d3161d1612a6e6f84c6b87c97f4525a88"}

#lean-gptf = {path = "/home/dwrensha/src/lean-gptf" }