[package]
name = "."
version = "0.1"
lean_version = "leanprover-community/lean:3.39.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "518b5d25c0dc227a0d1d230d055d1da5c5bef46e"}

#lean-gptf = {path = "/home/dwrensha/src/lean-gptf" }